<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Session\Store;
use Illuminate\Support\Facades\Storage;

class Image extends Model
{
    use HasFactory;

    protected $fillable = [
        'user_id',
        'category_id',
        'image_url',
        'thumbnail_url',
        'big_thumbnail_url',
        'blur_thumbnail_url',
        'status'
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function category()
    {
        return $this->belongsTo(ImageCategory::class, 'category_id');
    }

    public function getUrlAttribute()
    {
        return 'https://media.cooldreamy.com/' . str_replace('https://media.cooldreamy.com/', '', $this->image_url);
    }

    public function deleteWithImage($user_id){
        if($this->user_id = $user_id) {
            if(!is_null($this->image_url)) {
                $path = parse_url($this->image_url)['path'];
                Storage::delete("/images/".$path);
            }
            if(!is_null($this->thumbnail_url)) {
                $path = parse_url($this->thumbnail_url)['path'];
                Storage::delete("/images/".$path);
            }
            if(!is_null($this->blur_thumbnail_url)) {
                $path = parse_url($this->blur_thumbnail_url)['path'];
                Storage::delete("/images/".$path);
            }
            if(!is_null($this->big_thumbnail_url)) {
                $path = parse_url($this->big_thumbnail_url)['path'];
                Storage::delete("/images/".$path);
            }
        }
        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
